### PR TITLE
[iOS] Fix Popup bug where children lose TemplatedParent

### PR DESCRIPTION
**Pull request by fcantin-nventive**
## PR Type

Bugfix

## What is the current behavior?
ComboBox on iOS does not display its Popup

## What is the new behavior?
ComboBox on iOS now displays its Popup

## Other information
Internal issues: 136093  & 136172

### CODE REVIEW

**Comment by davidjohnoliver** [comment]
Why is the PopupPanel losing its TemplatedParent? Is this a recent regression?

**Comment by davidjohnoliver** [comment]
Also in the current code it looks like we create PopupPanel as a side-effect of the Popup.MainWindow property?? How does that even work?

**Comment by fcantin-nventive** [comment]
> Why is the PopupPanel losing its TemplatedParent? Is this a recent regression?

The PopupPanel never had a TemplatedParent, it was created directly by code in Popup.iOS.cs. The Popup's original children did have a TemplatedParent. When PopupPanel is inserted as the direct child of Popup, and the original children are set as children of PopupPanel, they inherit its TemplatedParent (which is null).

This has been the case for a while. The reason we recently saw a regression, is that ItemsPresenter used to not care about losing its TemplatedParent - as soon as it received it, it assumed it was loaded and set itself as the child of the ItemsControl. However, this assumption is no longer true and we added a check in ItemsPresenter to make sure that it is both loaded and has an ItemsControl PemplatedParent. This introduced a bug, because in the case of ComboBox, these two conditions were never simultaneously true.

**Comment by fcantin-nventive** [comment]
> Also in the current code it looks like we create PopupPanel as a side-effect of the Popup.MainWindow property?? How does that even work?

That is a mysterious behavior from the past! It seemed to be working OK, but I agree it's bizarre. I will push the changes we worked on together to move this creation to a more logical spot.

**Pull request merged**
