### PR TITLE
Updated references to support android 9 (pie)

### PR DESCRIPTION
**Pull request by mohaider**
Issue: #
133825
## PR Type

What kind of change does this PR introduce? 
Updated references to support android 9 (pie)

## What is the current behavior?
Uno currently doesn't have support for Android 9

## What is the new behavior?
Adds support for Android 9

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [X ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ X] Contains **NO** breaking changes

### CODE REVIEW

**Comment by jeromelaban** [comment]
This PR won't pass until hosted agents will be updated to a later version, we'll have to follow the azure devops team updates.

**Comment by MatFillion** [comment]
Hosted agents seem to have been updated.

**Comment by YGuerin** [comment]
@MatFillion @jeromelaban @jeremiethibeault : I'm actually working on notch for Android and I've based my branch on this one. I made it work on my branch. Should I update this one before or it will be ignored ?

**Comment by MatFillion** [comment]
yes @YGuerin include it in your own PR.

**Pull request closed without merging**
