### PR TITLE
XamlGeneration - exclude 'not_wasm' from WASM

### PR DESCRIPTION
**Pull request by davidjohnoliver**
GitHub Issue (If applicable): #784 

## PR Type
What kind of change does this PR introduce?

Bugfix 

## What is the current behavior?

`not_wasm` prefix in XAML wasn't taken into account.

## What is the new behavior?

Now taken into account.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by carldebilly** [comment]
We should rely on a namespace instead of just the prefix. The Uno approach is not XML compliant.

**Comment by davidjohnoliver** [comment]
> We should rely on a namespace instead of just the prefix. The Uno approach is not XML compliant.

Yeah the way we do this could be revisited at some point. The 'target', 'not_target' syntax is also a bit limited now that we have 5 different targets (UWP/Android/iOS/WASM/MacOS).

**Comment by jeromelaban** [comment]
Yes, now that UWP supports conditional xaml we should be adding support for that instead.

**Pull request merged**
