### PR TITLE
Updated the CheckBox checkmark glyph in the font to match UWP

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): -

## PR Type
What kind of change does this PR introduce?
 - Feature

## What is the current behavior?
The CheckBox checkmark is quite bold and does not match the UWP style.

## What is the new behavior?
Replaced the glyph in the used winjs-symbols font with a custom checkmark that matches the UWP style very closely:

WASM:
WASM
iOS:
ios
Android:
droid

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information
The glyph replacement in the font was done using https://www.glyphrstudio.com/online/ . I can provide the Glyphr Studio project file if necessary.

Internal Issue (If applicable):

https://nventive.visualstudio.com/Umbrella/_workitems/edit/123118

### CODE REVIEW

**Comment by agneszitte-nventive** [comment]
@jeromelaban  & @MatFillion For the drop-down arrow glyph for example for the ComboBox  (and other glyph) we can do the same ?

**Comment by MartinZikmund** [comment]
> @jeromelaban  & @MatFillion For the drop-down arrow glyph for example for the ComboBox  (and other glyphs) we can do the same?

We could, but I would vote for some automated approach - like maintaining a SVG file of used glyphs and completely ditch the winjs symbol font as it has different glyph positions as well as it no longer matches the _new_ MDL2 symbols.

This will take more effort though, as there are quite a lot of glyphs and each must be _remade_ manually. So it would make sense to maintain two fonts at first - the winjs as default and new "Uno MDL2 Assets" font winch we will slowly update with new glyphs as necessary.

It will also be easier as it was quite painful to replace the glyph in winjs font, whereas creating a new font from a glyph SVG file is quite simple and quick.

**Comment by agneszitte-nventive** [comment]
> > @jeromelaban  & @MatFillion For the drop-down arrow glyph for example for the ComboBox  (and other glyphs) we can do the same?
> 
> We could, but I would vote for some automated approach - like maintaining a SVG file of used glyphs and completely ditch the winjs symbol font as it has different glyph positions as well as it no longer matches the _new_ MDL2 symbols.
> 
> This will take more effort though, as there are quite a lot of glyphs and each must be _remade_ manually. So it would make sense to maintain two fonts at first - the winjs as default and new "Uno MDL2 Assets" font winch we will slowly update with new glyphs as necessary.
> 
> It will also be easier as it was quite painful to replace the glyph in winjs font, whereas creating a new font from a glyph SVG file is quite simple and quick.

Yes I liked the idea! @jeromelaban and @MatFillion any additional thoughts about that ?

**Comment by MatFillion** [comment]
We probably want a custom font (based from winjs or not). The important point is to keep UWP styles working without modifications, so we don't want to have to specify a different fontfamily in default styles of combobox or checkbox for example. That being said, we can only have 1 font, no?

**Comment by MartinZikmund** [comment]
We technically can have two fonts, but we will have to deploy them both (like a part of the template) until all the glyphs are "migrated" in the new font.

In addition to the glyphs looking a bit out of place in the winjs font the glyph Unicode codes are different from the Segoe MDL2 Assets font. So we really **need** a new custom font to make the templates match 1:1 with UWP.

**Comment by MartinZikmund** [comment]
Any additional changes needed here :-) ? @agneszitte-nventive @jeromelaban

**Comment by MartinZikmund** [comment]
This build failed, but the error does not appear to be caused by anything the PR touched, could you please try to re-run it?

**Comment by ghuntley** [comment]
Have lifted the conversation regarding automating glyphs and moved it over to here https://github.com/nventive/Uno/issues/967 as an item on the backlog as `help wanted`.

**Comment by ghuntley** [comment]
Thank you @MartinZikmund for this pull-request. We appreciate you and all that you do for Uno. Wanna jump on a video call sometime and do a virtual ☕ date? Pick a time over at https://ghuntley.com/meet

**Pull request merged**
