### PR TITLE
[iOS] Add ListView.UseCollectionAnimations flag

### PR DESCRIPTION
**Pull request by davidjohnoliver**
Allows native insert/delete animations to be disabled when undesired or as a workaround when they're glitchy.

GitHub Issue (If applicable): #

## PR Type
What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

https://nventive.visualstudio.com/Umbrella/_workitems/edit/150793

### CODE REVIEW

**Comment by MatFillion** [comment]
Should you add a note in a ListView.md file ?
Maybe https://github.com/nventive/Uno/blob/master/doc/articles/ListViewBase.md ?

**Comment by davidjohnoliver** [comment]
> Should you add a note in a ListView.md file ?
> Maybe https://github.com/nventive/Uno/blob/master/doc/articles/ListViewBase.md ?

Good idee

**Pull request merged**
